In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [17]:
data = pd.read_csv("../../datasets/oral_toxicity/qsar_oral_toxicity.csv", header=None, sep = ';');

In [18]:
col_names = [f"f{i}" for i in range(data.shape[1] - 1)] + ["target"]
data.columns = col_names

In [19]:
data["target"] = data["target"].map({"negative": 0, "positive": 1})

In [20]:
data.head()

,f0,f1,f2,f3,f4,f5,f6,f7,f8,f9,...,f1015,f1016,f1017,f1018,f1019,f1020,f1021,f1022,f1023,target
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
X = data.drop("target",axis=1)
X.head()

,f0,f1,f2,f3,f4,f5,f6,f7,f8,f9,...,f1014,f1015,f1016,f1017,f1018,f1019,f1020,f1021,f1022,f1023
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
y = data[["target"]]
y.head()

   target
0       0
1       0
2       0
3       0
4       0

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,stratify=y,test_size=0.3)
X_train,X_validation,y_train,y_validation = train_test_split(X_train,y_train,test_size = 0.3,stratify = y_train)

In [23]:
scaler = StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [25]:
X_train = pd.DataFrame(X_train,columns=X.columns)
X_test = pd.DataFrame(X_test,columns=X.columns)

In [26]:
X_train.to_csv("../../datasets/oral_toxicity/X_train.csv", index=False)
X_test.to_csv("../../datasets/oral_toxicity/X_test.csv", index=False)

y_train.to_csv("../../datasets/oral_toxicity/y_train.csv", index=False)
y_test.to_csv("../../datasets/oral_toxicity/y_test.csv", index=False)