In [72]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [73]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
ionosphere = fetch_ucirepo(id=52) 
  
# data (as pandas dataframes) 
X = ionosphere.data.features 
y = ionosphere.data.targets 
  
# metadata 
#print(ionosphere.metadata) 
  
# variable information 
#print(ionosphere.variables)

In [74]:
y

    Class
0       g
1       b
2       g
3       b
4       g
..    ...
346     g
347     g
348     g
349     g
350     g

[351 rows x 1 columns]

In [75]:
y.loc[:, 'Class'] = y['Class'].map({'g': 0, 'b': 1}).astype(int)

In [76]:
y

    Class
0       0
1       1
2       0
3       1
4       0
..    ...
346     0
347     0
348     0
349     0
350     0

[351 rows x 1 columns]

In [77]:
X_train,X_test,y_train,y_test = train_test_split(X,y,stratify=y,test_size=0.3)

In [78]:
scaler = StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [79]:
X_train = pd.DataFrame(X_train,columns=X.columns)
X_test = pd.DataFrame(X_test,columns=X.columns)

In [80]:
X_train.to_csv("../../datasets/ionosphere/X_train.csv", index=False)
X_test.to_csv("../../datasets/ionosphere/X_test.csv", index=False)

y_train.to_csv("../../datasets/ionosphere/y_train.csv", index=False)
y_test.to_csv("../../datasets/ionosphere/y_test.csv", index=False)